name: Electron Forge Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'

      - name: Install Dependencies
        run: |
          npm ci

      - name: Package Electron App
        run: |
          npx electron-forge package
        env:
          CI: true

      - name: Install 7-Zip
        run: |
          choco install 7zip
            
      - name: Zip LapLoot Folder with 7-Zip
        run: |
          7z a -tzip -mx=9 LapLoot "out\LapLoot\*"
        shell: cmd

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LapLoot.zip
          path: LapLoot
          retention-days: 90
          compression-level: 0
          
    