name: Electron Forge Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'

      - name: Install Dependencies
        run: |
          npm ci

      - name: Package Electron App
        run: |
          npx electron-forge package
        env:
          CI: true

      - name: Zip LapLoot Folder
        run: |
          powershell Compress-Archive -Path "out\LapLoot" -DestinationPath "LapLoot.zip"
        shell: pwsh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LapLoot.zip
          path: LapLoot.zip
          retention-days: 90
          compression-level: 9
          
    